import Notification from '@/models/Notification';
import Member from '@/models/Member';
import ChitGroup from '@/models/ChitGroup';
import GroupMember from '@/models/GroupMember';
import { sendToMember, interpolateTemplate, isPushConfigured } from '@/lib/pushService';

/**
 * Fire-and-forget event-driven notification helpers.
 * These should be called after successful DB operations
 * — they catch all errors internally so they never break the parent request.
 */

/** Notify a member that their payment was recorded */
export async function notifyPaymentConfirmation(opts: {
    memberId: string;
    memberName: string;
    groupName: string;
    groupId: string;
    amountPaid: number;
    periodNumber: number;
}) {
    if (!isPushConfigured()) return;

    try {
        const body = interpolateTemplate(
            'Your payment of ₹{{amount}} for "{{groupName}}" (Period {{period}}) has been recorded. Thank you!',
            {
                amount: opts.amountPaid.toLocaleString('en-IN'),
                groupName: opts.groupName,
                period: opts.periodNumber,
            }
        );

        const notif = await Notification.create({
            title: 'Payment Confirmed',
            body,
            url: `/groups/${opts.groupId}`,
            priority: 'normal',
            targetType: 'MEMBER',
            targetId: opts.memberId,
            notificationType: 'PAYMENT_CONFIRMATION',
            autoGenerated: true,
            status: 'SENT',
            sentAt: new Date(),
        });

        const result = await sendToMember(opts.memberId, {
            title: 'Payment Confirmed',
            body,
            url: `/groups/${opts.groupId}`,
            tag: `payment-${opts.groupId}-${opts.memberId}`,
        });

        notif.successCount = result.sent;
        notif.failCount = result.failed;
        await notif.save();
    } catch (e) {
        console.error('Event notification (PAYMENT_CONFIRMATION) failed:', e);
    }
}

/** Notify a member that they won the chit prize */
export async function notifyWinnerAnnouncement(opts: {
    memberId: string;
    memberName: string;
    groupName: string;
    groupId: string;
    prizeAmount: number;
    periodNumber: number;
}) {
    if (!isPushConfigured()) return;

    try {
        const body = interpolateTemplate(
            'Congratulations {{memberName}}! 🎉 You won the chit prize of ₹{{prize}} for "{{groupName}}" (Period {{period}}).',
            {
                memberName: opts.memberName,
                prize: opts.prizeAmount.toLocaleString('en-IN'),
                groupName: opts.groupName,
                period: opts.periodNumber,
            }
        );

        const notif = await Notification.create({
            title: '🏆 You Won the Chit!',
            body,
            url: `/winners`,
            priority: 'urgent',
            targetType: 'MEMBER',
            targetId: opts.memberId,
            notificationType: 'WINNER_ANNOUNCEMENT',
            autoGenerated: true,
            status: 'SENT',
            sentAt: new Date(),
        });

        const result = await sendToMember(opts.memberId, {
            title: '🏆 You Won the Chit!',
            body,
            url: `/winners`,
            priority: 'urgent',
            tag: `winner-${opts.groupId}-${opts.periodNumber}`,
        });

        notif.successCount = result.sent;
        notif.failCount = result.failed;
        await notif.save();
    } catch (e) {
        console.error('Event notification (WINNER_ANNOUNCEMENT) failed:', e);
    }
}

/** Notify a member they have been enrolled in a group */
export async function notifyEnrollment(opts: {
    memberId: string;
    groupName: string;
    groupId: string;
    units: number;
    totalDue: number;
}) {
    if (!isPushConfigured()) return;

    try {
        const body = interpolateTemplate(
            'You have been enrolled in "{{groupName}}" with {{units}} unit(s). Total contribution: ₹{{totalDue}}.',
            {
                groupName: opts.groupName,
                units: opts.units,
                totalDue: opts.totalDue.toLocaleString('en-IN'),
            }
        );

        const notif = await Notification.create({
            title: 'Group Enrollment',
            body,
            url: `/groups/${opts.groupId}`,
            priority: 'normal',
            targetType: 'MEMBER',
            targetId: opts.memberId,
            notificationType: 'ENROLLMENT',
            autoGenerated: true,
            status: 'SENT',
            sentAt: new Date(),
        });

        const result = await sendToMember(opts.memberId, {
            title: 'Group Enrollment',
            body,
            url: `/groups/${opts.groupId}`,
            tag: `enrollment-${opts.groupId}-${opts.memberId}`,
        });

        notif.successCount = result.sent;
        notif.failCount = result.failed;
        await notif.save();
    } catch (e) {
        console.error('Event notification (ENROLLMENT) failed:', e);
    }
}
