import mongoose, { Schema, Document } from 'mongoose';

export interface INotification extends Document {
    title: string;
    body: string;
    url?: string;
    icon?: string;
    image?: string;
    priority: 'normal' | 'urgent';
    targetType: 'ALL' | 'ORGANISATION' | 'USER' | 'MEMBER' | 'GROUP';
    targetId?: mongoose.Types.ObjectId;
    notificationType?: string;
    autoGenerated?: boolean;
    status: 'DRAFT' | 'SCHEDULED' | 'SENT' | 'FAILED';
    scheduledAt?: Date;
    sentAt?: Date;
    successCount: number;
    failCount: number;
    templateId?: mongoose.Types.ObjectId;
    createdBy?: mongoose.Types.ObjectId;
    createdAt: Date;
    updatedAt: Date;
}

const NotificationSchema = new Schema<INotification>({
    title: { type: String, required: true, maxlength: 100 },
    body: { type: String, required: true, maxlength: 500 },
    url: { type: String },
    icon: { type: String },
    image: { type: String },
    priority: {
        type: String,
        enum: ['normal', 'urgent'],
        default: 'normal'
    },
    targetType: {
        type: String,
        enum: ['ALL', 'ORGANISATION', 'USER', 'MEMBER', 'GROUP'],
        default: 'ALL'
    },
    targetId: {
        type: Schema.Types.ObjectId,
    },
    notificationType: {
        type: String,
        enum: [
            'GENERAL',
            'PAYMENT_REMINDER',
            'OVERDUE_ALERT',
            'PAYMENT_CONFIRMATION',
            'WINNER_ANNOUNCEMENT',
            'ENROLLMENT',
            'GROUP_STARTED',
            'GROUP_COMPLETED'
        ],
        default: 'GENERAL'
    },
    autoGenerated: {
        type: Boolean,
        default: false
    },
    status: {
        type: String,
        enum: ['DRAFT', 'SCHEDULED', 'SENT', 'FAILED'],
        default: 'DRAFT'
    },
    scheduledAt: Date,
    sentAt: Date,
    successCount: { type: Number, default: 0 },
    failCount: { type: Number, default: 0 },
    templateId: {
        type: Schema.Types.ObjectId,
        ref: 'NotificationTemplate',
    },
    createdBy: {
        type: Schema.Types.ObjectId,
        ref: 'User',
    }
}, {
    timestamps: true
});

// Indexes for query performance
NotificationSchema.index({ status: 1, createdAt: -1 });
NotificationSchema.index({ status: 1, scheduledAt: 1 });
NotificationSchema.index({ createdBy: 1 });
NotificationSchema.index({ targetType: 1, targetId: 1 });
NotificationSchema.index({ notificationType: 1, autoGenerated: 1 });

export default mongoose.models.Notification ||
    mongoose.model<INotification>('Notification', NotificationSchema);
